collator/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from logger.views import TrafficListView, add_traffic, EventCreatePop, get_cat_id

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login.urls')),
    path('logger/', include(('logger.urls', 'logger'), namespace='logger')),
    # path('traffic/', TrafficListView.as_view(), name='log_sheet'),
    # path('submit/', add_traffic, name='add_traffic'), # For some reason if I erase this path, the one from logger/urls.py won't work
    url(r'create_cat/', EventCreatePop, name = 'CategoryCreate'),
    url(r'^category/ajax/get_cat_id', get_cat_id, name = "get_cat_id"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

logger/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from logger.views import TrafficListView, TagView

app_name = 'logger'

urlpatterns = [
    path('submit/', views.add_traffic, name='add_traffic'),
    path('', views.trafficIndex, name = 'tagged_traffic'),
    path('tag/<slug:tag_slug>/', views.TagView, name = 'tagged_traffic'),
    path('traffic/', TrafficListView.as_view(), name='log_sheet'),
    path('<slug:traffic_post>/', views.traffic_detail, name='traffic_detail'),
    ]

login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # path('login/', views.user_login, name='login')
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    #Change password urls
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    #Reset password urls
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    
    path('register/', views.register, name='register'),
    
    path('edit/', views.edit, name='edit'),
    
    path('validate_username', views.validate_username, name='validate_username'),
    
    #User account details
    path('users/', views.user_list, name='user_list'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    
]

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    dintegrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/css/tagsinput.css" />
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light border-bottom box-shadow mb-3">
    <a href="#" class="navbar-brand">4CENT</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <div class="navbar-nav">
        <a href="{% url 'logger:add_traffic' %}" class="nav-item nav-link">Submit</a>
        <a href="{% url 'logger:log_sheet' %}" class="nav-item nav-link">Traffic Log Sheet</a>
        <a href="{% url 'user_list' %}" class="nav-item nav-link">Browse Users</a>
        <a href="#" class="nav-item nav-link disabled" tabindex="-1">Reports</a>
      </div>
      {% endif %}
      <div class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <div class="nav-item nav-link">
          Hello {{ request.user.first_name }},
        </div>
        <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
        {% else %}
        <a href="{% url 'login' %}" class="nav-item nav-link">Log-in</a>
        {% endif %}
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
        {% endfor %}
        {% block content %}
        {% endblock %}
</body>

</div>
</div>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript">
  < script src = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity = "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
  crossorigin = "anonymous" >
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>
<script src="/static/js/tagsinput.js"></script>

<script>
  function showEditPopup(url) {
    var win = window.open(url, "Edit",
      'height=500,width=800,resizable=yes,scrollbars=yes');
    return false;
  }

  function showAddPopup(triggeringLink) {
    var name = triggeringLink.id.replace(/^add_/, '');
    href = triggeringLink.href;
    var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;
  }

  function closePopup(win, newID, newRepr, id) {
    $(id).append('<option value=' + newID + ' selected>' + newRepr + '</option>')
    win.close();
  }
</script>
{% block script %}
{% endblock %}



</html>